title: Jaz-Marie
email: contact@jaz-marie.com
description: > # this means to ignore newlines until "baseurl:"
  All about me and my life and stuff (update this later)
baseurl: "" # the subpath of your site, e.g. /blog
url: "jaz-marie.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  itsonlyjaz

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

